#TODO delete this file when everything works
#Nota: para cuando quiera cambiar la documentación de las funciones roxygen2::roxygenize()
#inputData = t(matrix(c(3,2,3.5,12,4.7,4.1,5.2,4.9,7.1,6.1,6.2,5.2,14,5.3),2,7,dimnames=list(c("r","d"))))
#inputData = data.frame(inputData)
#print(inputData)
#inputData <- transform_to_vector(inputData)
#print(inputData)
#boxandwhiskers(inputData,2,TRUE)
#boxandwhiskers(inputData,2,FALSE)
data = c(1,2,3,4,1,6,10,20)
q1 = quantile(data, 0.25)
q2 = quantile(data, 0.5)
q3 = quantile(data, 0.75)
